name: Octo Build Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: |
          pip3 install pipenv wheel
      - name: Clean Environment
        run: |
          make clean
      - name: Consume Dependencies
        run: |
          make venv
      - name: Build and Test
        run: |
          make build
      - name: Publish
        run: |
          make publish
        if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == '3.8' }}
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - name: Version
        id: version
        uses: juliangruber/read-file-action@v1
        if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == '3.8' }}
        with:
          path: ./VERSION
      - name: Tag
        uses: rickstaa/action-create-tag@v1
        if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == '3.8' }}
        with:
          tag: "${{ steps.version.outputs.content }}"
