name: Octo Build Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: |
          pip3 install pipenv wheel
      - name: Clean Environment
        run: |
          make clean
      - name: Consume Dependencies
        run: |
          make venv
      - name: Build and Test
        run: |
          make build
